# name: PagerDuty Auto Ack

# on:
#   schedule:
#     # Every 5 minutes on Sunday (UTC!)
#     - cron: "*/5 * * * 0"

#   workflow_dispatch:  # allows manual trigger

# jobs:
#   run-script:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Setup Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.11"

#       - name: Install deps
#         run: pip install -r requirements.txt

#       - name: Run script
#         env:
#           PD_API_KEY: ${{ secrets.PD_API_KEY }}
#           PD_USER_EMAIL: ${{ secrets.PD_USER_EMAIL }}
#         run: python script.py
